# Generated by Django 5.1.2 on 2024-10-14 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogcontentmodel',
            name='image',
            field=models.ImageField(default=False, upload_to='images'),
        ),
    ]
